version: "3.8"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # persistência dos modelos
    restart: unless-stopped

volumes:
  ollama_models:
